# Generated by Django 4.2.7 on 2026-07-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelisting',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='PasswordResetCode',
        ),
    ]
